### ISSUE TITLE
CGB_IR.kicad_sch component Q4 has mixed the legs base and emitter.

### ISSUE THREAD

**Issue by giltesa** [nataliethenerd/CGB_ReverseEngineer#1]
Hello Natalie,

I checked your file CGB_IR.kicad_sch and I think the component **Q4** has mixed the legs **base** and **emitter**.

In your schematic the **base** is connected to **Q5** and the **emitter** to **R23**, however the Game Boy Color Service Manual and my game boy color mainboard have their **base** connected to **R23** and **emitter** to **Q5**.

Kind regards,
giltesa

**Comment by nataliethenerd** [comment]
Working on fixing this, thank you Giltesa!
